rabbitmq:
  host: broker
  port: 5672
  username: user
  password: password
  exchange_name: asyncio_observer
  queue_name: processed_file
#  exchange_type: direct
  routing_key: observer

observer:
  watched_folder: /data/in
  buf_size: 1024
