rabbitmq:
  host: brocker
  port: 5672
  username: user
  password: password
  exchange: asyncio_observer
#  exchange_type: direct
  routing_key: observer

observer:
  watched_folder: /data/in
  buf_size: 1024
