version: '3'

services:
  observer:
    build:
      context: ./observer
    volumes:
      - /tmp/wyll:/data/in
    networks:
      - asyncio_project
    depends_on:
      broker:
        condition: service_healthy

  broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    hostname: broker
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - asyncio_project

networks:
  asyncio_project:

volumes:
  rabbitmq_data: